name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: thecloudschool-project-id
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/thecloudschool-project-id/devops-cicd-demo:latest .
          docker push gcr.io/thecloudschool-project-id/devops-cicd-demo:latest

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials devops-cluster --zone asia-south1-a --project thecloudschool-project-id

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/devops-demo-deployment devops-demo=gcr.io/thecloudschool-project-id/devops-cicd-demo:latest
