name: Build, Push to Docker Hub, and Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-cicd-demo:latest .

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Push Docker image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-cicd-demo:latest

      # Step 5: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 6: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ✅ Step 7: Install the GKE Auth Plugin (this is the missing piece)
      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # Step 8: Configure kubectl
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials devops-demo-cluster --zone asia-south1 --project ${{ secrets.GCP_PROJECT_ID }}

      # Step 9: Deploy new image to GKE
      - name: Deploy new image to GKE
        run: |
          kubectl set image deployment/devops-demo-deployment devops-demo=${{ secrets.DOCKER_USERNAME }}/devops-cicd-demo:latest
          kubectl rollout status deployment/devops-demo-deployment
